use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

# Do not print debug messages in production
config :logger, level: :info, backends: [:console, RingLogger]

database_url =
  System.get_env("DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

discord_token =
  System.get_env("DISCORD_TOKEN") ||
    raise """
    environment variable DISCORD_TOKEN is missing.
    """

config :chromoid, Chromoid.Repo,
  # ssl: true,
  url: database_url,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

config :chromoid, ChromoidWeb.Endpoint,
  url: [host: "chromo.id", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  secret_key_base: secret_key_base,
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ]

config :nostrum, token: discord_token
